config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: { registrations: 'registrations' }
  root 'pages#timeline'

  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end

  get 'tweeters', to: 'users#index'

  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create, :edit, :update, :destroy  ]
  resources :likes, only: [:create, :destroy], param: :likeable_id
  resources :comments, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  post :notifications, to:'notifications#mark_all_read'

  resources :mentions, only: [:index]
  get 'pages/timeline'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include PublicActivity::Model

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  validates_presence_of :comment
  
  FORMAT = AutoHtml::Pipeline.new(
    AutoHtml::HtmlEscape.new,
    AutoHtml::Link.new(target: '_blank', rel: 'nofollow'),
    AutoHtml::SimpleFormat.new
)

def content=(c)
    super(c)
    self[:content_html] = FORMAT.call(c)
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_commentable, only: :create
  respond_to :js

  def create
    @comment = @commentable.comments.new do |comment|
      comment.comment = params[:comment_text]
      comment.user = current_user
    end
    @comment.save
    @comment.create_activity key: 'comment.created', owner: current_user, recipient: @commentable.user
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
  end

  private
  
  def find_commentable
    @commentable_type = params[:commentable_type].classify
    @commentable = @commentable_type.constantize.find(params[:commentable_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="card-footer">
    <%= gravatar_tag comment.user.email, size: 25, :html => { :class => 'img-fluid' } %> <%= comment.user.username %> رد على تغريدة <%= content_tag :time, '', class: 'timeago', datetime: comment.created_at.localtime %>
    <% if user_signed_in? && current_user == comment.user %>
      <%= link_to('حذف',comment_path(comment), method: :delete, remote: true, class: 'btn btn-sm btn-danger') %>
    
    <% end %>
  </div>
  <div class="card-body">
    <%= raw(comment.comment) %>
  </div>
</div>

app/views/comments/_form.html.erb
<p class="text-center mb-0">عدد الردود: <span id="comments-<%= tweet.id %>-count"><%= tweet.comments.size %></span></p>
<%= form_tag comments_path(commentable_type: 'tweet', commentable_id: tweet.id), method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag :comment_text, nil, placeholder: 'ردك', class: 'form-control' %>
  </div>
  <%= submit_tag 'رد', class: 'btn btn-sm btn-primary' %>
<% end %>

app/views/comments/create.js.erb
$('#comments-<%= @comment.commentable.id %>').prepend('<%= j render @comment %>');

val = $('#comments-<%= @comment.commentable.id %>-count').text();
$('#comments-<%= @comment.commentable.id %>-count').text(parseInt(val) + 1);

$('.tweet-<%= @comment.commentable.id %> #comment_text').val('');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();

val = $('#comments-<%= @comment.commentable.id %>-count').text();
$('#comments-<%= @comment.commentable.id %>-count').text(parseInt(val) - 1);