config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: { registrations: 'registrations' }
  root 'pages#timeline'

  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end

  get 'tweeters', to: 'users#index'

  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create, :edit, :update, :destroy  ]
  resources :likes, only: [:create, :destroy], param: :likeable_id
  resources :comments, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  post :notifications, to:'notifications#mark_all_read'

  resources :mentions, only: [:index]
  get 'pages/timeline'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/retweet.rb
class Retweet < ApplicationRecord
    include PublicActivity::Model

    validates_uniqueness_of :retweeter_id, scope: :source_tweet_id
    
    belongs_to :retweeter, class_name: 'User'
    belongs_to :source_tweet, class_name: 'Tweet'
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :authenticate_user!

  def create
    retweet = current_user.retweets.new(source_tweet_id: params[:tweet_id])
    if retweet.save
      retweet.create_activity key: 'retweet.created', owner: current_user, recipient: retweet.source_tweet.user
      redirect_to user_path(current_user.username), notice: 'تم إعادة التغريد'
    else
      redirect_back fallback_location: root_path, alert: 'تم اعادة التغريدة مسبقا!'
    end
  end

  def destroy
    retweet = current_user.retweets.find(params[:id])
    retweet.destroy
    redirect_to user_path(current_user.username), notice: 'تم حذف إعادة التغريد'
  end
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/views/retweets/_retweet.html.erb
<div class="card tweet-<%= retweet.source_tweet.id %>">
  <div class="card-header bg-success border-success text-white">
    قام <%= retweet.retweeter.username %> بإعادة تغريد هذا <%= content_tag :time, '', class: 'timeago', datetime: retweet.created_at.localtime %>
    <% if user_signed_in? && current_user == retweet.retweeter %>
      <%= link_to 'حذف', retweet_path(retweet), method: :delete, class: 'badge badge-danger' %>
    <% end %>
  </div>
  <div class="card-header">
    <%= gravatar_tag retweet.source_tweet.user.email, size: 25, :html => { :class => 'img-fluid' } %> <%= retweet.source_tweet.user.username %> غرّد <%= content_tag :time, '', class: 'timeago', datetime: retweet.source_tweet.created_at.localtime %>
    <% if user_signed_in? && current_user == retweet.source_tweet.user %>
      <%= link_to('تعديل', edit_tweet_path(retweet.source_tweet), class: 'btn btn-sm btn-primary') %> | <%= link_to('حذف', tweet_path(retweet.source_tweet), method: :delete, class: 'btn btn-sm btn-danger') %>
    <% end %>
  </div>
  <div class="card-body pb-0">
    <%= raw(retweet.source_tweet.content_html) %>
    <%= render 'tweets/like_and_dislike_buttons', tweet: retweet.source_tweet %>
    <%= render 'tweets/retweet_button', tweet: retweet.source_tweet if user_signed_in? && retweet.source_tweet.user_id != current_user.id %>
  </div>
  <hr>
  <div class="card-body">
    <%= render 'comments/form', tweet: retweet.source_tweet %>
  </div>
  <div id="comments-<%= retweet.source_tweet.id %>">
    <%= render retweet.source_tweet.comments.reverse %>
  </div>
</div>

<br>
 