config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: { registrations: 'registrations' }
  root 'pages#timeline'

  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end

  get 'tweeters', to: 'users#index'

  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create, :edit, :update, :destroy  ]
  resources :likes, only: [:create, :destroy], param: :likeable_id
  resources :comments, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  post :notifications, to:'notifications#mark_all_read'

  resources :mentions, only: [:index]
  get 'pages/timeline'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PublicActivity::Model
    after_create :resolve_mentions

    acts_as_votable
    acts_as_commentable

    belongs_to :user

    has_many :retweets, dependent: :destroy, foreign_key: 'source_tweet_id'

    validates_presence_of :content
    validates_length_of :content, maximum: 140

    FORMAT = AutoHtml::Pipeline.new(
        AutoHtml::HtmlEscape.new,
        AutoHtml::Link.new(target: '_blank', rel: 'nofollow'),
        AutoHtml::SimpleFormat.new
    )

    def content=(c)
        super(c)
        self[:content_html] = FORMAT.call(c)
    end
    def resolve_mentions
        mentions = content_html.scan(/@\w+/)
        mentions.uniq.map do |match|
            mention = find_mention(match)
            next unless mention
            update_attributes!(content_html: replace_mention_with_url(mention, content_html))
            create_activity key: 'tweet.mention', owner: user, recipient: mention
        end
    end

    def find_mention(match)
        user = User.find_by(username: match.delete('@'))
        user if user.present?
    end
    def replace_mention_with_url(mention, content)
        content.gsub(/@#{mention.username}/, "<a href='#{Rails.application.routes.url_helpers.user_path(mention.username)}' target='_blank'>@#{mention.username}</a>")
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, except: [:create]

  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      @tweet.create_activity key: 'tweet.created', owner: @tweet.user
      redirect_to user_path(@tweet.user.username), notice: 'تم إنشاء التغريدة'
    else
      redirect_to user_path(@tweet.user.username), notice: 'حدث شيء خاطئ!'
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to user_path(@tweet.user.username), notice: 'تم تعديل التغريدة'
    else
      redirect_to user_path(@tweet.user.username), notice: 'حدث شيء خاطئ'
    end  
  end

  def destroy
    @tweet.destroy
    redirect_to user_path(@tweet.user.username), notice: 'تم حذف التغريدة'
  end


  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <div class="card">
    <div class="card-header">غرّد الان!</div>
    <div class="card-body">
      <%= f.error_notification %>
      <%= f.input :content, required: true, autofocus: true, label: false, hint: "#{140 - @tweet.content.to_s.length}", input_html: { class: 'form-control', maxlength: 140, onkeyup: 'updateChars(this); return true;' } %>
      <%= f.button :submit, 'غرّد', class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

<br>

<%= javascript_tag do %>
  function updateChars(text) {
  $('.tweet_content .help-block').text(140 - text.value.length);
  }

  jQuery(function() {
  $('#tweet_content').atwho({
  at: '@',
  callbacks: {
  remoteFilter: function(query, callback) {
  if (query.length < 1) {
  return false;
  } else {
  return $.getJSON('/users.json', {
  q: query
  }, function(data) {
  return callback(data);
  });
  }
  }
  }
  });
  });
<% end %>

app/views/tweets/_like_and_dislike_buttons.html.erb
<%= link_to likes_path(likeable_type: 'tweet', likeable_id: tweet.id), remote: true, method: :post, class: 'like' do %>
  <%= button_tag(type: 'button', class: 'btn btn-sm btn-outline-primary') do %>
    <%= fa_icon 'thumbs-o-up'%> <span class="badge badge-light"><%= tweet.get_likes.size %></span>
  <% end %>
<% end %>
<%= link_to like_path(likeable_type: 'tweet', likeable_id: tweet.id), remote: true, method: :delete, class: 'dislike' do %>
  <%= button_tag(type: 'button', class: 'btn btn-sm btn-outline-danger') do %>
        <%= fa_icon 'thumbs-o-down'%>    <span class="badge badge-light"><%= tweet.get_dislikes.size %></span>
  <% end %>
<% end %>

app/views/tweets/_retweet_button.html.erb
<%= link_to retweets_path(tweet_id: tweet.id), method: :post, class: 'retweet' do %>
  <button type="button" class="btn btn-sm btn-success">
    <%= fa_icon 'retweet'%> <span class="badge badge-light"><%= tweet.retweets.size %></span>
  </button>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card tweet-<%= tweet.id %>">
  <div class="card-header">
    <%= gravatar_tag tweet.user.email, size: 25, :html => { :class => 'img-fluid' } %> <%= tweet.user.username %> غرّد <%= content_tag :time, '', class: 'timeago', datetime: tweet.created_at.localtime %>
    <% if user_signed_in? && current_user == tweet.user %>
      <%= link_to('تعديل',edit_tweet_path(tweet), class: 'btn btn-sm btn-primary') %> | <%= link_to('حذف',tweet_path(tweet), method: :delete, class: 'btn btn-sm btn-danger')  %>
    <% end %>
  </div>
  <div class="card-body" style="padding-bottom:0px">
    <%= raw(tweet.content_html) %>
    <%= render 'tweets/like_and_dislike_buttons',tweet: tweet %>
    <%= render 'tweets/retweet_button', tweet: tweet if user_signed_in? && tweet.user_id != current_user.id %>
       <hr>
    <div class="card-body">
      <%= render 'comments/form', tweet: tweet %>
    </div>
    <div id="comments-<%= tweet.id %>">
      <%= render tweet.comments.reverse %>
</div>
  </div>
</div>

<br>

app/views/tweets/edit.html.erb
<div class="row">
  <div class="col-6 offset-md-3">
    <%= render 'form' %>
  </div>
</div>