config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: { registrations: 'registrations' }
  root 'pages#timeline'

  resources :users, only: [:index, :show] do
    member do
      get :following
      get :followers
    end
  end

  get 'tweeters', to: 'users#index'

  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:create, :edit, :update, :destroy  ]
  resources :likes, only: [:create, :destroy], param: :likeable_id
  resources :comments, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  post :notifications, to:'notifications#mark_all_read'

  resources :mentions, only: [:index]
  get 'pages/timeline'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_voter

  validates_presence_of :username
  validates_uniqueness_of :username

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
    
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :tweets, dependent: :destroy

  has_many :comments, dependent: :destroy
  
  has_many :retweets, dependent: :destroy, foreign_key: 'retweeter_id'

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by_followed_id(user.id).destroy
  end

  def following?(user)
    following.include? user
  end
  def self.mentions(letters)
    return User.none unless letters.present?
    users = User.limit(8).where('username like ?', "#{letters}%")
    users.map{ |user| {name: user.username}}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :followers, :following]
  before_action :authenticate_user!, only: [:index]

  def index

      case params[:type]
      when 'following'
        @users = current_user.following.order(created_at: :desc)
      when 'followers'
        @users = current_user.followers.order(created_at: :desc)
      else
       @users =User.all.order(created_at: :desc)
      end
      respond_to do |format|
        format.html
        format.json{render :json => User.mentions(params[:q])}
      end
  end

  def show
    @tweet = Tweet.new
    @tweets = @user.retweets + @user.tweets
    @tweets.sort_by!(&:created_at).reverse!
    @activities = PublicActivity::Activity.where(owner: @user) + PublicActivity::Activity.where(recipient: @user)
    @activities.uniq!
    @activities.sort_by!(&:created_at).reverse!
  end

  def followers
    @users = @user.followers.order(created_at: :desc)
  end

  def following
    @users = @user.following.order(created_at: :desc)
  end


  private

  def set_user
   @user = User.find_by_username(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
<% if user_signed_in? && current_user.id != user.id %>
  <% if current_user.following? user %>
    <%= form_for current_user.active_relationships.find_by_followed_id(user.id), html: { method: :delete } do |f| %>
      <%= f.submit 'إلغاء المتابعة', class: 'btn btn-secondary' %>
    <% end %>
  <% else %>
    <%= form_for current_user.active_relationships.build do |f| %>
      <%= hidden_field_tag :followed_id, user.id %>
      <%= f.submit 'متابعة', class: 'btn btn-dark' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<div class="col-3">
  <div class="card">
    <%= link_to user_path(user.username) do %>
      <%= gravatar_tag user.email, size: 200, html: { class: 'card-img-top img-fluid' } %>
    <% end %>
    <div class="card-body">
      <h4 class="card-title text-center mb-0">
        <%= user.username %>
        <%= render 'follow_button', user: user %>
      </h4>
    </div>
  </div>
  <br>
</div>

app/views/users/followers.html.erb
<div class="row">
  <div class="col">
    <div class="jumbotron-fluid">
      <center>
        <h1 class="display-5">أشخاص يُتابعون <%= @user.username %></h1>
      </center>
      <hr class="my-3">
    </div>
  </div>
</div>

<div class="container">
  <div class="row flex-row-reverse">
    <%= render @users %>
  </div>
</div>

app/views/users/following.html.erb
<div class="row">
  <div class="col">
    <div class="jumbotron-fluid">
      <center>
        <h1 class="display-5">أشخاص تابعهم <%= @user.username %></h1>
      </center>
      <hr class="my-3">
    </div>
  </div>
</div>

<div class="container">
  <div class="row flex-row-reverse">
    <%= render @users %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col">
    <div class="jumbotron-fluid">
      <center>
        <h1 class="display-5">المغردون</h1>
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to 'الكل', tweeters_path, class: 'btn btn-dark' %>
          <%= link_to 'المُتابَعون', tweeters_path(type: 'following'), class: 'btn btn-dark' %>
          <%= link_to 'المُتابِعون', tweeters_path(type: 'followers'), class: 'btn btn-dark' %>
        </div>
      </center>
      <hr class="my-3">
    </div>
  </div>
</div>

<div class="container">
  <div class="row flex-row-reverse">
    <%= render @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row flex-row-reverse">
  <div class="col-3">
    <%= gravatar_tag @user.email, size: 500, :html => { :class => 'img-fluid' } %>
  </div>
  <div class="col">
    <div class="jumbotron-fluid">
      <h1 class="display-3">
       <%= @user.username %>
        <span class="btn-group">
        <%= render 'follow_button', user: @user %>
        </span>
      
      </h1>
        
         <p class="lead">
          <%= link_to 'المُتابِعون', followers_user_path(@user.username) %>: <%= @user.followers.count %>
          | 
          <%= link_to 'المُتابَعون', following_user_path(@user.username) %>: <%= @user.following.count %>
         </p>

      <p> العمر <%= @user.age %></p>
      <p> الجنس <%= @user.gender%></p>
      <hr class="my-3">
      <h1 class="lead">عن نفسي !</h1>
      <p class="lead"><%= @user.bio%></p>

    </div>
  </div>
</div>

<br>

<div class="row">
  <div class="container">
    <div class="row">
      <div class="col-8">
              <% if user_signed_in? && current_user == @user %>
          <%= render 'tweets/form' %>
               
        <% end %>
   <%= render @tweets %>

      </div>
      
      <div class="col-4">
        <div class="card">
          <div class="card-header">
            <%= fa_icon 'list', text: 'الأنشطة' %>
          </div>
          <% unless @activities.blank? %>
          <ul class="list-group list-group-flush">
            <%= render_activities(@activities) %>
          </ul>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>